### ISSUE TITLE
CORE - 개발환경 세팅

### ISSUE THREAD

**Issue by dl-00-e8** [Mews-MIS/Mews-Server#1]
## IssueName
CORE - 개발환경 세팅

## Description
CI/CD 구축

## Todo
 - [ ]  EC2 인스턴스 도커 설치
 - [ ] Github Actions 스크립트 파일 생성
 - [ ] github-actions.yml 
 - [ ]  branch 연결
 - [ ] Jdk Setting
 - [ ] Gradle Caching 설정
 - [ ] properties 파일 설정
 - [ ] Gradle Build 및 도커 Build & push
 - [ ] Deploy to AWS EC2 (SSH Connection) 설정
